# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn global add @angular/cli
          - yarn
          - ng build
          - ng test --watch=false --browsers ChromeHeadless
          #- npm install
          #- npm test  cant be run at BitBucket pipeline now, 
          # IT WILL HANG AND CONSUME OUR ACCOUNT CLOUD BUILD TIME FOR THE MONTH