# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.9.4

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
          - node-global
          - yarn
        script:
          - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.18.1
          - export PATH=$HOME/.yarn/bin:$PATH
          - yarn global add @angular/cli@1.7.0
          - yarn
          - ng test --watch false --browser PhantomJS --single-run
    - step:
        name: Build Docker Image
        caches:
          - yarn
        script:
          - yarn
          # - ng build --target=production --base-href /
          - ng build --base-href /
          - docker build .

definitions:
  caches:
    node-global: /usr/local/lib/node_modules
    yarn: $HOME/.cache/yarn

options:
  docker: true
