# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
pipelines:
  default:
    - step:
        name: Build and Test
        image: afekosystem/ng-builder
        caches:
          - node
          - node-global
        script:
          - ng test --watch false --browser PhantomJS --single-run
          # - ng build --target=production --base-href /
          - ng build --base-href /
        artifacts:
          -  dist/**
    - step:
        name: Build Docker Image
        script:
          - docker build .

definitions:
  caches:
    node-global: /usr/local/lib/node_modules

options:
  docker: true
